export const ADD_TASK = "ADD_TASK";
export const COMPLETE_ACTIVE_TASK = "COMPLETE_ACTIVE_TASK";
export const EDIT_ACTIVE_TASK = "EDIT_ACTIVE_TASK";
export const SAVE_ACTIVE_TASK = "SAVE_ACTIVE_TASK";
export const DELETE_ACTIVE_TASK = "DELETE_ACTIVE_TASK";
export const TERMINATE_COMPLETED_TASK = "TERMINATE_COMPLETED_TASK";
